### ISSUE TITLE
Frage zu Pumpensteuerung

### ISSUE THREAD

**Issue by AzonInc** [100prznt/VarioControl#2]
Hi,

kann man damit ggfs. auch die eingestellte Pumpengeschwindigkeit auslesen?

Und könnte man die Pumpe ggfs auch per PWM Signal steuern? Ich habe leider keine Dokumentation zu dem Board gefunden. Es ist eine Aqua Vario Plus Filterpumpe.

![image](https://github.com/100prznt/VarioControl/assets/11911587/ac548f57-b70d-430c-b04c-59c3b589a699)

Grüße
Florian

**Comment by 100prznt** [comment]
Habe zahlreiche versuche unternommen und bin zu dem Schluss gekommen, dass der PWM Pin bei der Aqua Vario Plus ohne Funktion ist, bzw. sich nicht per Software aktivieren lässt.

Generell lässt sich nichts auslesen, es sind alles Eingänge. Wenn die Pumpe ferngesteuert wird, muss ja aber auch nichts zurück gelesen werden. Die Sollwerte stehen ja im Controller (VarioControl) bereit und können jederzeit rück gelesen werden.
Ein Mischbetrieb (mit manueller Steuerung über die Taster an der Pumpe) wird nicht unterstützt.

Beste Grüße Elias

**Comment by AzonInc** [comment]
Schade, aber danke für die Info :)
